{% set version = "0.3.5" %}

package:
  name: campo
  version: {{ version }}


source:
  url: https://campo.computationalgeography.org/download/sources/campo-{{ version }}.tar.bz2
  sha256: b6564745b66af0a6c29ffce41144ab9cb15a6f92886ad0d24184177a4d91c1e8


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - numpy
    - lue >=0.3.7
    - hpx 1.9.0
    - pcraster
    - xarray
    - pandas
    - gdal
    - networkx


about:
  home: https://campo.computationalgeography.org/
  license: MIT
  license_file: LICENSE.txt
  summary: Modelling framework for fields and agents
  description: |
    Campo is an environmental modelling framework for the construction of
    spatio-temporal models with support for field-based and agent-based
    phenomena. Campo provides the elementary building blocks for the
    construction and execution of field-agent models: operations accepting
    both fields and agents as arguments, and operations that are dedicated
    either to fields or to agents. Campo resembles and extends the map algebra
    approach to field-agent modelling and allows for the construction of static
    or dynamic models.
  doc_url: https://campo.computationalgeography.org/documentation/index.html
  dev_url: https://github.com/computationalgeography/campo


extra:
  recipe-maintainers:
    - OliverSchmitz
    - kordejong
